version: '3.8'

services:
    flask-app:
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - postgres
            - kafka
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/mydatabase
            - KAFKA_BROKER=kafka:9092

    postgres:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: mydatabase
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    zookeeper:
        image: confluentinc/cp-zookeeper:7.5.0
        restart: always
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    kafka:
        image: confluentinc/cp-kafka:7.5.0
        restart: always
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        ports:
            - "9092:9092"

volumes:
    pgdata:
